apiVersion: v1
kind: Service
metadata:
  name: apache-struts
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: apache-struts
